Repository 2noise/ChatTTS, pull requests merged in 2024-08, with the labels that each got.

#666 typo: README
  README.md
Labels: documentation

#669 feat: add [--source ***] [--custom_path XXX] for run cmd
  examples/__init__.py
  examples/cmd/run.py
Labels: enhancement, ui

#679 Add finetuning support for `Speaker` class
  ChatTTS/model/speaker.py
Labels: enhancement

#737 Fix device mismatch error in embedding loading on branch dev
  ChatTTS/core.py
  ChatTTS/model/dvae.py
  ChatTTS/model/embed.py
Labels: bug, enhancement

#738 fix idx error when do repetition penalty
  ChatTTS/model/velocity/model_runner.py
Labels: bug, algorithm
