Repository 2noise/ChatTTS, pull requests merged in 2024-10, with the labels that each got.

#777 Add NPU Support
  ChatTTS/core.py
  ChatTTS/utils/gpu.py
Labels: enhancement, performance

#733 Update dvae.py and change param gamma to weight
  ChatTTS/model/dvae.py
Labels: bug, algorithm

#778 docs: add README.kr
  README.md
  docs/cn/README.md
  docs/es/README.md
  docs/fr/README.md
  docs/jp/README.md
  docs/kr/README.md
  docs/ru/README.md
Labels: documentation, enhancement

#788 Fix for Ascend NPU when using ChatTTS to sample the voice of a real speaker
  ChatTTS/core.py
Labels: bug, enhancement
