Repository 2noise/ChatTTS, pull requests merged in 2024-06, with the labels that each got.

#33 在README中更新了star曲线
  README.md
  README_CN.md
Labels: documentation

#172 Update webui.py
  webui.py
Labels: enhancement

#199 docs; add Japanese README
  README.md
  README_CN.md
  README_JP.md
Labels: documentation

#241 Grammar correction for README.md
  README.md
Labels: documentation

#261 Add apple gpu mps backend
  ChatTTS/utils/gpu_utils.py
Labels: enhancement

#283 Update README.md
  README.md
Labels: documentation

#305 add setup.py
  README.md
  README_CN.md
  setup.py
Labels: enhancement

#36 Update README.md
  README.md
Labels: documentation

#342 Update README_CN.md
  README_CN.md
Labels: documentation

#340 chore: add ignore to asset and config folder
  .gitignore
Labels: documentation

#343 fix: normalizer fallback & mps infer
  ChatTTS/core.py
  ChatTTS/model/gpt.py
  requirements.txt
Labels: bug, documentation, enhancement

#21 add app.py and update README.md
  README.md
  cmd.py
Labels: documentation, enhancement

#273 Improve code
  ChatTTS/model/dvae.py
Labels: enhancement, algorithm

#182 Optimized weui
  webui.py
Labels: ui

#208 optimize: tqdm display to jump directly to max_new_token at completion
  ChatTTS/model/gpt.py
Labels: bug, algorithm

#351 fix: rename cmd to run to avoid package name conflict
  run.py
Labels: bug, ui

#353 doc: move scripts into examples
  .gitignore
  README.md
  examples/cmd/run.py
  examples/ipynb/colab.ipynb
  examples/ipynb/example.ipynb
  examples/web/webui.py
Labels: documentation, enhancement, ui

#356 add Related Resources
  README.md
Labels: documentation

#355 add Installation
  README.md
Labels: documentation

#357 doc: optimize README
  README.md
Labels: documentation

#358 doc: optimize README
  README.md
Labels: documentation

#359 doc: optimize README
  README.md
Labels: documentation

#350 [Fix] Replace mispronounced words in TTS using hack method
  ChatTTS/core.py
  ChatTTS/res/homophones_map.json
  ChatTTS/utils/infer_utils.py
Labels: enhancement, good first issue

#361 feat(core): add load_models source `local`
  .github/workflows/checksum.yml
  ChatTTS/core.py
  ChatTTS/utils/download.py
  examples/cmd/run.py
  examples/web/webui.py
  requirements.txt
  sha256.env
  tools/checksum/main.go
  tools/checksum/tmpl.go
Labels: enhancement, ui

#360 support stream mode
  ChatTTS/core.py
  ChatTTS/infer/api.py
  ChatTTS/model/gpt.py
Labels: enhancement, algorithm

#363 fix: stream api
  ChatTTS/core.py
  ChatTTS/infer/api.py
  ChatTTS/model/gpt.py
Labels: bug, algorithm

#364 doc: translate README
  docs/cn/README.md
Labels: documentation

#365 doc: fix the readme link
  docs/cn/README.md
Labels: documentation

#367 doc: optimize README
  README.md
Labels: documentation

#368 doc: optimize README
  README.md
Labels: documentation

#374 doc: optimize README
  README.md
Labels: documentation

#373 Ensuring logits scores are contiguous resolved the bug on MPS
  ChatTTS/utils/infer_utils.py
Labels: algorithm

#377 Windows not yet supported for torch.compile fix
  ChatTTS/core.py
Labels: bug, enhancement

#379 fix(ipy): missing envs
  examples/ipynb/colab.ipynb
  examples/ipynb/example.ipynb
Labels: ui

#383 optimize(dvae): remove einops
  ChatTTS/model/dvae.py
Labels: enhancement, algorithm

#387 [fix] Adjust GPU memory check threshold
  ChatTTS/core.py
Labels: bug

#389 fix: mps memory leakage by moving gpt&emb to cpu
  ChatTTS/core.py
  ChatTTS/infer/api.py
  ChatTTS/model/gpt.py
  ChatTTS/utils/io.py
  ChatTTS/utils/io_utils.py
  requirements.txt
  setup.py
Labels: bug, enhancement

#380 add stream mode in webui
  examples/web/webui.py
Labels: enhancement, ui

#390 doc: release requirements limit
  requirements.txt
Labels: documentation

#391 fix: model loading check
  ChatTTS/core.py
  examples/cmd/run.py
  examples/web/webui.py
Labels: bug

#392 fix(examples): ipnyb infer
  ChatTTS/model/gpt.py
  examples/ipynb/example.ipynb
  examples/web/webui.py
Labels: bug, documentation, algorithm

#393 fix(examples): colab infer
  examples/ipynb/colab.ipynb
Labels: bug, documentation

#394 doc: optimize README
  docs/cn/README.md
Labels: documentation

#398 optimize: log & webui
  ChatTTS/core.py
  ChatTTS/model/gpt.py
  ChatTTS/utils/download.py
  ChatTTS/utils/gpu_utils.py
  ChatTTS/utils/infer_utils.py
  ChatTTS/utils/io.py
  ChatTTS/utils/log.py
  examples/cmd/run.py
  examples/web/funcs.py
  examples/web/webui.py
  tools/logger/__init__.py
  tools/logger/log.py
Labels: enhancement, ui

#397 refactor: revise the Load Models part of examples/ipynb
  examples/ipynb/colab.ipynb
  examples/ipynb/example.ipynb
Labels: documentation, enhancement, ui

#399 fix(req): restrict normalizer' installation to linux
  requirements.txt
Labels: bug, documentation

#401 fix(tools): log formatting
  examples/cmd/run.py
  examples/web/funcs.py
  requirements.txt
  setup.py
  tools/audio/__init__.py
  tools/audio/np.py
  tools/logger/log.py
Labels: bug, ui

#366 add tests for stream mode.
  examples/cmd/run.py
Labels: enhancement, ui

#403 fix(dvae): dvae _embed permute mismatch
  ChatTTS/model/dvae.py
Labels: bug, enhancement, algorithm

#405 feat(dvae): expose coef for customize
  ChatTTS/core.py
  ChatTTS/model/dvae.py
  requirements.txt
  setup.py
Labels: enhancement, algorithm

#407 optimize(gpt): apply type definitions
  ChatTTS/core.py
  ChatTTS/infer/api.py
  ChatTTS/model/dvae.py
  ChatTTS/model/gpt.py
  ChatTTS/utils/io.py
Labels: documentation, enhancement, algorithm

#408 fix(core): local download path
  ChatTTS/utils/download.py
Labels: bug

#409 fix(dvae): given NumPy array is not writable
  ChatTTS/model/dvae.py
Labels: bug

#410 feat(ipynb): apply logger to notebook
  examples/ipynb/colab.ipynb
  examples/ipynb/example.ipynb
  tools/logger/log.py
Labels: documentation, enhancement

#411 optimize: log printing
  examples/ipynb/colab.ipynb
  tools/logger/log.py
Labels: enhancement, ui

#415 optimize: all
  ChatTTS/core.py
  ChatTTS/model/dvae.py
  ChatTTS/model/gpt.py
  ChatTTS/utils/dl.py
  ChatTTS/utils/gpu.py
  ChatTTS/utils/infer.py
  ChatTTS/utils/io.py
  ChatTTS/utils/log.py
  examples/ipynb/colab.ipynb
  examples/ipynb/example.ipynb
  examples/web/funcs.py
  examples/web/webui.py
  tools/audio/np.py
  tools/logger/log.py
  tools/seeder/__init__.py
  tools/seeder/ctx.py
Labels: bug, documentation, enhancement, algorithm, ui, performance

#414 Add init.py to tools and web to fix launching webui demo
  examples/web/__init__.py
  tools/__init__.py
Labels: bug, ui

#413 Disable torch.compile on Windows for webui demo
  examples/web/funcs.py
  examples/web/webui.py
Labels: bug, ui

#416 optimize(chat): move gpt&decoders out of dict
  ChatTTS/core.py
  ChatTTS/infer/api.py
  ChatTTS/utils/dl.py
  examples/web/funcs.py
Labels: enhancement

#419 optimize(utils): move custom processors into model
  ChatTTS/core.py
  ChatTTS/infer/api.py
  ChatTTS/model/gpt.py
  ChatTTS/model/processors.py
  ChatTTS/utils/gpu.py
  ChatTTS/utils/infer.py
Labels: enhancement

#421 doc: optimize README
  README.md
Labels: documentation

#422 optimize: specify infer parameters
  ChatTTS/core.py
  ChatTTS/infer/api.py
  ChatTTS/model/gpt.py
  ChatTTS/model/processors.py
  examples/web/funcs.py
Labels: documentation, enhancement, algorithm, performance

#427 doc: sync to latest grammar
  ChatTTS/core.py
  ChatTTS/model/gpt.py
  ChatTTS/norm.py
  ChatTTS/utils/gpu.py
  README.md
  examples/ipynb/colab.ipynb
  examples/ipynb/example.ipynb
  examples/web/funcs.py
  tools/llm/__init__.py
  tools/llm/llm.py
  tools/logger/log.py
Labels: documentation, enhancement

#428 fix(norm): wrong type check to function (fix #423)
  ChatTTS/norm.py
  examples/ipynb/colab.ipynb
  examples/ipynb/example.ipynb
  examples/web/funcs.py
Labels: bug, documentation

#430 fix(colab): color log printing
  examples/ipynb/colab.ipynb
  tools/logger/log.py
Labels: documentation, enhancement

#429 fix(install): incomplete installation
  ChatTTS/model/__init__.py
  ChatTTS/res/__init__.py
  ChatTTS/utils/__init__.py
  setup.py
Labels: bug

#431 feat: normalize imports
  ChatTTS/core.py
  ChatTTS/model/__init__.py
  ChatTTS/model/gpt.py
  ChatTTS/norm.py
  ChatTTS/utils/__init__.py
  setup.py
Labels: documentation, enhancement

#432 refactor: Chat.load_model to Chat.load
  ChatTTS/core.py
  README.md
  docs/cn/README.md
  docs/jp/README.md
  docs/ru/README.md
  examples/cmd/run.py
  examples/ipynb/colab.ipynb
  examples/ipynb/example.ipynb
  examples/web/funcs.py
Labels: enhancement

#433 feat: interruptible infer
  ChatTTS/__init__.py
  ChatTTS/core.py
  ChatTTS/model/gpt.py
  examples/web/funcs.py
  examples/web/webui.py
Labels: documentation, enhancement, algorithm, ui

#441 fix(load): KeyError: 'sha256_config_decoder_yaml' (fix #438)
  ChatTTS/core.py
  ChatTTS/model/gpt.py
  ChatTTS/res/sha256_map.json
  ChatTTS/utils/dl.py
  examples/cmd/run.py
  examples/ipynb/colab.ipynb
  examples/ipynb/example.ipynb
  examples/web/webui.py
  requirements.txt
  sha256.env
  tools/checksum/main.go
  tools/checksum/tmpl.go
Labels: bug, documentation, enhancement

#442 feat(workflow): add useful actions
  .github/workflows/close-issue.yml
  .github/workflows/push-format.yml
  .github/workflows/unitest.yml
  .github/workflows/upload-pypi.yml
  setup.py
Labels: documentation, enhancement

#445 doc: add new contacts
  README.md
Labels: documentation

#446 doc: optimize README
  README.md
Labels: documentation

#449 feat(examples): use mp3 output by default
  .gitignore
  README.md
  docs/cn/README.md
  docs/jp/README.md
  docs/ru/README.md
  examples/cmd/run.py
  examples/web/webui.py
  requirements.txt
  tools/audio/__init__.py
  tools/audio/av.py
Labels: enhancement, ui

#451 optimize(model): more torch funcalls
  ChatTTS/model/gpt.py
  ChatTTS/model/processors.py
  examples/web/ex.py
  examples/web/funcs.py
  examples/web/webui.py
Labels: bug, enhancement

#452 fix(setup): README decoding issue
  setup.py
Labels: bug

#453 feat(chat): add model check to custom load
  ChatTTS/core.py
  ChatTTS/utils/dl.py
Labels: enhancement

#454 fix(core): mps infer incorrect on some device (fix #444)
  ChatTTS/core.py
  ChatTTS/model/__init__.py
  ChatTTS/model/processors.py
  ChatTTS/utils/dl.py
Labels: bug, algorithm

#457 fix(setup): invalid version (fix #456)
  .github/workflows/unitest.yml
  setup.py
Labels: bug

#461 optimize: spk_emb & generate & webui
  .github/workflows/unitest.yml
  ChatTTS/core.py
  ChatTTS/model/gpt.py
  examples/ipynb/colab.ipynb
  examples/ipynb/example.ipynb
  examples/web/funcs.py
  examples/web/webui.py
Labels: bug, enhancement, algorithm

#458 fix docs
  docs/cn/README.md
  docs/es/README.md
  docs/jp/README.md
  docs/ru/README.md
Labels: documentation

#463 feat: use `str` type `spk_emb` for easy recovery
  ChatTTS/core.py
  README.md
  docs/cn/README.md
  docs/es/README.md
  docs/jp/README.md
  docs/ru/README.md
  examples/ipynb/colab.ipynb
  examples/ipynb/example.ipynb
Labels: enhancement, algorithm

#464 fix: redundant `[spk_emb]`s in refine_text (fix #459)
  ChatTTS/core.py
Labels: bug, algorithm

#466 fix(webui): crash on non-ffmpeg env.
  examples/cmd/run.py
  examples/web/funcs.py
  examples/web/webui.py
  tools/audio/__init__.py
  tools/audio/mp3.py
Labels: bug, ui

#467 feat(webui): support external spk_emb
  examples/web/funcs.py
  examples/web/webui.py
Labels: enhancement, ui

#469 fix(webui): input textbox not editable
  examples/web/webui.py
Labels: bug, ui

#472 perf: use cpu in MacOS by default
  ChatTTS/core.py
  ChatTTS/utils/gpu.py
  examples/cmd/run.py
Labels: algorithm, performance

#474 feat(chat): add hidden api `_encode_spk_emb`
  ChatTTS/core.py
Labels: documentation, enhancement

#483 fix(webui): specify every interactive=True (fix #482)
  examples/web/webui.py
Labels: bug, ui

#480 fix: _encode_spk_emb use 'tobytes' without check 'dtype'
  ChatTTS/core.py
Labels: enhancement

#486 optimize(webui): unify initial value to ex[0]
  examples/web/webui.py
Labels: ui

#489 fix(dl): type obj not subscriptable on some py ver
  ChatTTS/utils/dl.py
Labels: bug

#493 fix(webui): fallback to wav if ffmpeg not installed
  examples/web/funcs.py
  examples/web/webui.py
  requirements.txt
  tools/audio/__init__.py
  tools/audio/ffmpeg.py
Labels: bug, ui

#495 optimize(_apply_spk_emb): expand after F.normalize
  ChatTTS/core.py
Labels: enhancement, algorithm

#496 perf(gpt): add NVIDIA accelerated TELlamaModel
  ChatTTS/core.py
  ChatTTS/model/cuda/__init__.py
  ChatTTS/model/cuda/te_llama.py
  ChatTTS/model/gpt.py
Labels: enhancement, algorithm, performance

#498 doc: add TransformerEngine installation instruction
  README.md
  examples/ipynb/colab.ipynb
Labels: documentation
