Repository 2noise/ChatTTS, pull requests merged in 2024-07, with the labels that each got.

#509 doc: sync latest README
  docs/cn/README.md
Labels: documentation

#512 cmd/jupyter流式播放代码；add stream display example in cmd/jupyter mode
  examples/cmd/stream.py
  requirements.txt
Labels: enhancement, ui

#533 Add language: franch
  README.md
  docs/cn/README.md
  docs/es/README.md
  docs/fr/README.md
  docs/jp/README.md
  docs/ru/README.md
Labels: documentation

#546 fix(api): fix order of args for writestr
  examples/api/main.py
Labels: bug, ui

#638 降低zero-shot功能对torch版本的要求
  ChatTTS/core.py
  ChatTTS/model/tokenizer.py
Labels: enhancement, algorithm

#622 Add scripts to support onnx export
  examples/onnx/README.md
  examples/onnx/exporter.py
  examples/onnx/gpt.py
  examples/onnx/modeling_llama.py
Labels: enhancement

#642 fix: topK and topP not valid
  ChatTTS/core.py
Labels: bug, good first issue, algorithm
